// <auto-generated />
using System;
using BankServiceBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BankServiceBackend.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20201116192801_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BankServiceBackend.Entities.Account", b =>
                {
                    b.Property<long>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("Credit")
                        .HasColumnType("double precision");

                    b.Property<double>("Dispo")
                        .HasColumnType("double precision");

                    b.Property<string>("HashedPin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserCustomerNumber")
                        .HasColumnType("bigint");

                    b.HasKey("AccountNumber");

                    b.HasIndex("UserCustomerNumber");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankServiceBackend.Entities.User", b =>
                {
                    b.Property<long>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BankServiceBackend.Entities.Account", b =>
                {
                    b.HasOne("BankServiceBackend.Entities.User", null)
                        .WithMany("Accounts")
                        .HasForeignKey("UserCustomerNumber");
                });

            modelBuilder.Entity("BankServiceBackend.Entities.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
